package com.myanmar.ledger2d.core.repository

import androidx.room.withTransaction

import com.myanmar.ledger2d.core.database.*
import com.myanmar.ledger2d.core.domain.BetParser
import com.myanmar.ledger2d.core.domain.QuickFormat
import com.myanmar.ledger2d.core.model.*
import kotlinx.coroutines.flow.Flow
import java.time.LocalDate

interface AgentRepository { fun observeAll(): Flow<List<AgentEntity>>; fun observe(id: Long): Flow<AgentEntity?>; suspend fun get(id: Long): AgentEntity?; suspend fun save(value: AgentEntity): Long }
interface CustomerRepository { fun observeForAgent(agentId: Long): Flow<List<CustomerEntity>>; fun observe(id: Long): Flow<CustomerEntity?>; suspend fun get(id: Long): CustomerEntity?; suspend fun getForAgent(agentId: Long): List<CustomerEntity>; suspend fun save(value: CustomerEntity): Long }
interface BetRepository { fun observeCustomerTotals(customerId: Long, date: LocalDate, session: DrawSession): Flow<List<DigitTotalRow>>; fun observeAgentTotals(agentId: Long, date: LocalDate, session: DrawSession): Flow<List<DigitTotalRow>>; fun observeEntry(id: Long): Flow<BetEntryWithLines?>; suspend fun getEntry(id: Long): BetEntryWithLines?; fun observeCustomerEntries(customerId: Long): Flow<List<BetEntryWithLines>>; suspend fun getCustomerTotals(customerId: Long, date: LocalDate, session: DrawSession): Map<String, Long>; suspend fun getAgentTotals(agentId: Long, date: LocalDate, session: DrawSession): Map<String, Long>; suspend fun confirm(customerId: Long, agentId: Long, date: LocalDate, session: DrawSession, source: String, format: QuickFormat, bets: List<ExpandedBet>): Long; suspend fun edit(entry: BetEntryEntity, bets: List<ExpandedBet>, format: QuickFormat); suspend fun delete(entry: BetEntryEntity) }
interface WinningNumberRepository { fun observeAll(): Flow<List<WinningNumberEntity>>; fun observe(date: LocalDate, session: DrawSession): Flow<WinningNumberEntity?>; suspend fun get(date: LocalDate, session: DrawSession): WinningNumberEntity?; suspend fun save(date: LocalDate, session: DrawSession, digit: String): Long; suspend fun delete(value: WinningNumberEntity) }
interface ClosedDayRepository { fun observeAll(): Flow<List<ClosedDayEntity>>; suspend fun isClosed(date: LocalDate): Boolean; suspend fun add(date: LocalDate): Long; suspend fun remove(value: ClosedDayEntity) }
interface ClosedNumberRepository { fun observe(agentId: Long): Flow<List<ClosedNumberEntity>>; suspend fun getDigits(agentId: Long): Set<String>; suspend fun add(agentId: Long, digit: String): Long; suspend fun remove(value: ClosedNumberEntity) }
interface LimitRepository { fun observeAllLimit(customerId: Long): Flow<AllLimitEntity?>; fun observeSpecial(customerId: Long): Flow<List<SpecialLimitEntity>>; suspend fun get(customerId: Long): EffectiveLimits; suspend fun setAll(customerId: Long, amount: Long?); suspend fun setSpecial(customerId: Long, digit: String, amount: Long); suspend fun deleteSpecial(value: SpecialLimitEntity) }
interface AgentLimitRepository { fun observeAllLimit(agentId: Long): Flow<AgentAllLimitEntity?>; fun observeSpecial(agentId: Long): Flow<List<AgentSpecialLimitEntity>>; suspend fun get(agentId: Long): EffectiveLimits; suspend fun setAll(agentId: Long, amount: Long?); suspend fun setSpecial(agentId: Long, digit: String, amount: Long); suspend fun deleteSpecial(value: AgentSpecialLimitEntity) }

class RoomAgentRepository(private val dao: AgentDao): AgentRepository { override fun observeAll()=dao.observeAll(); override fun observe(id:Long)=dao.observe(id); override suspend fun get(id:Long)=dao.get(id); override suspend fun save(value:AgentEntity)=dao.upsert(value) }
class RoomCustomerRepository(private val dao: CustomerDao): CustomerRepository { override fun observeForAgent(agentId:Long)=dao.observeForAgent(agentId); override fun observe(id:Long)=dao.observe(id); override suspend fun get(id:Long)=dao.get(id); override suspend fun getForAgent(agentId:Long)=dao.getForAgent(agentId); override suspend fun save(value:CustomerEntity)=dao.upsert(value) }
class RoomBetRepository(private val db: LedgerDatabase): BetRepository {
    private val dao=db.betDao()
    override fun observeCustomerTotals(customerId:Long,date:LocalDate,session:DrawSession)=dao.observeCustomerTotals(customerId,date,session)
    override fun observeAgentTotals(agentId:Long,date:LocalDate,session:DrawSession)=dao.observeAgentTotals(agentId,date,session)
    override fun observeEntry(id:Long)=dao.observeEntry(id)
    override suspend fun getEntry(id:Long)=dao.getEntry(id)
    override fun observeCustomerEntries(customerId:Long)=dao.observeCustomerEntries(customerId)
    override suspend fun getCustomerTotals(customerId:Long,date:LocalDate,session:DrawSession)=dao.getCustomerTotals(customerId,date,session).associate { it.digit to it.amount }
    override suspend fun getAgentTotals(agentId:Long,date:LocalDate,session:DrawSession)=dao.getAgentTotals(agentId,date,session).associate { it.digit to it.amount }
    private fun validateLines(bets:List<ExpandedBet>) { require(bets.isNotEmpty()); require(bets.all { com.myanmar.ledger2d.core.domain.BetParser.validDigit(it.digit) && it.amount > 0 }); require(bets.map { it.digit }.distinct().size == bets.size) }
    override suspend fun confirm(customerId:Long,agentId:Long,date:LocalDate,session:DrawSession,source:String,format:QuickFormat,bets:List<ExpandedBet>):Long = db.withTransaction { validateLines(bets); require(source.isNotBlank()); val now=System.currentTimeMillis(); val id=dao.insertEntry(BetEntryEntity(customerId=customerId,agentId=agentId,drawDate=date,drawSession=session,sourceText=source,inputFormat=format.name,createdAt=now,updatedAt=now)); dao.insertLines(bets.map { BetLineEntity(betEntryId=id,digit=it.digit,amount=it.amount) }); id }
    override suspend fun edit(entry:BetEntryEntity,bets:List<ExpandedBet>,format:QuickFormat) = db.withTransaction { validateLines(bets); require(entry.sourceText.isNotBlank()); val old=dao.getEntry(entry.id)?.entry ?: error("Bet entry not found"); require(db.winningNumberDao().get(old.drawDate,old.drawSession)==null); require(db.winningNumberDao().get(entry.drawDate,entry.drawSession)==null); dao.updateEntry(entry.copy(inputFormat=format.name,updatedAt=System.currentTimeMillis())); dao.deleteLines(entry.id); dao.insertLines(bets.map { BetLineEntity(betEntryId=entry.id,digit=it.digit,amount=it.amount) }) }
    override suspend fun delete(entry:BetEntryEntity) = db.withTransaction { require(db.winningNumberDao().get(entry.drawDate,entry.drawSession)==null); dao.deleteEntry(entry) }
}
class RoomWinningNumberRepository(private val db:LedgerDatabase):WinningNumberRepository { private val dao=db.winningNumberDao(); override fun observeAll()=dao.observeAll(); override fun observe(date:LocalDate,session:DrawSession)=dao.observe(date,session); override suspend fun get(date:LocalDate,session:DrawSession)=dao.get(date,session); override suspend fun save(date:LocalDate,session:DrawSession,digit:String):Long { require(BetParser.validDigit(digit)); val now=System.currentTimeMillis(); val old=dao.get(date,session); require(old==null || db.betDao().countEntries(date,session)==0); return dao.upsert(WinningNumberEntity(id=old?.id?:0,date=date,session=session,digit=digit,createdAt=old?.createdAt?:now,updatedAt=now)) }; override suspend fun delete(value:WinningNumberEntity) { require(db.betDao().countEntries(value.date,value.session)==0); dao.delete(value) } }
class RoomClosedDayRepository(private val dao:ClosedDayDao):ClosedDayRepository { override fun observeAll()=dao.observeAll(); override suspend fun isClosed(date:LocalDate)=dao.isClosed(date); override suspend fun add(date:LocalDate):Long { require(!date.isBefore(LocalDate.now())); val now=System.currentTimeMillis(); val old=dao.get(date); return dao.upsert(ClosedDayEntity(id=old?.id?:0,date=date,createdAt=old?.createdAt?:now,updatedAt=now)) }; override suspend fun remove(value:ClosedDayEntity)=dao.delete(value) }
class RoomClosedNumberRepository(private val dao:ClosedNumberDao):ClosedNumberRepository { override fun observe(agentId:Long)=dao.observe(agentId); override suspend fun getDigits(agentId:Long)=dao.getDigits(agentId).toSet(); override suspend fun add(agentId:Long,digit:String):Long { require(com.myanmar.ledger2d.core.domain.BetParser.validDigit(digit)); val now=System.currentTimeMillis(); val old=dao.get(agentId,digit); return dao.upsert(ClosedNumberEntity(id=old?.id?:0,agentId=agentId,digit=digit,createdAt=old?.createdAt?:now,updatedAt=now)) }; override suspend fun remove(value:ClosedNumberEntity)=dao.delete(value) }
class RoomLimitRepository(private val dao:LimitDao):LimitRepository { override fun observeAllLimit(customerId:Long)=dao.observeAllLimit(customerId); override fun observeSpecial(customerId:Long)=dao.observeSpecialLimits(customerId); override suspend fun get(customerId:Long)=EffectiveLimits(dao.getAllLimit(customerId)?.amount,dao.getSpecialLimits(customerId).associate { it.digit to it.amount }); override suspend fun setAll(customerId:Long,amount:Long?) { if(amount==null) dao.clearAll(customerId) else { require(amount>0); val now=System.currentTimeMillis(); val old=dao.getAllLimit(customerId); dao.upsert(AllLimitEntity(id=old?.id?:0,customerId=customerId,amount=amount,createdAt=old?.createdAt?:now,updatedAt=now)) } }; override suspend fun setSpecial(customerId:Long,digit:String,amount:Long) { require(com.myanmar.ledger2d.core.domain.BetParser.validDigit(digit)&&amount>0); val now=System.currentTimeMillis(); val old=dao.getSpecial(customerId,digit); dao.upsert(SpecialLimitEntity(id=old?.id?:0,customerId=customerId,digit=digit,amount=amount,createdAt=old?.createdAt?:now,updatedAt=now)) }; override suspend fun deleteSpecial(value:SpecialLimitEntity)=dao.delete(value) }
class RoomAgentLimitRepository(private val dao:AgentLimitDao):AgentLimitRepository { override fun observeAllLimit(agentId:Long)=dao.observeAllLimit(agentId); override fun observeSpecial(agentId:Long)=dao.observeSpecialLimits(agentId); override suspend fun get(agentId:Long)=EffectiveLimits(dao.getAllLimit(agentId)?.amount,dao.getSpecialLimits(agentId).associate { it.digit to it.amount }); override suspend fun setAll(agentId:Long,amount:Long?) { if(amount==null) dao.clearAll(agentId) else { require(amount>0); val now=System.currentTimeMillis(); val old=dao.getAllLimit(agentId); dao.upsert(AgentAllLimitEntity(id=old?.id?:0,agentId=agentId,amount=amount,createdAt=old?.createdAt?:now,updatedAt=now)) } }; override suspend fun setSpecial(agentId:Long,digit:String,amount:Long) { require(BetParser.validDigit(digit)&&amount>0); val now=System.currentTimeMillis(); val old=dao.getSpecial(agentId,digit); dao.upsert(AgentSpecialLimitEntity(id=old?.id?:0,agentId=agentId,digit=digit,amount=amount,createdAt=old?.createdAt?:now,updatedAt=now)) }; override suspend fun deleteSpecial(value:AgentSpecialLimitEntity)=dao.deleteSpecial(value) }
