package com.myanmar.ledger2d.core.repository

import androidx.room.withTransaction

import com.myanmar.ledger2d.core.database.*
import com.myanmar.ledger2d.core.model.*
import kotlinx.coroutines.flow.Flow
import java.time.LocalDate

interface AgentRepository { fun observeAll(): Flow<List<AgentEntity>>; fun observe(id: Long): Flow<AgentEntity?>; suspend fun get(id: Long): AgentEntity?; suspend fun save(value: AgentEntity): Long }
interface CustomerRepository { fun observeForAgent(agentId: Long): Flow<List<CustomerEntity>>; fun observe(id: Long): Flow<CustomerEntity?>; suspend fun get(id: Long): CustomerEntity?; suspend fun save(value: CustomerEntity): Long }
interface BetRepository { fun observeCustomerTotals(customerId: Long, date: LocalDate, session: DrawSession): Flow<List<DigitTotalRow>>; fun observeAgentTotals(agentId: Long, date: LocalDate, session: DrawSession): Flow<List<DigitTotalRow>>; suspend fun getCustomerTotals(customerId: Long, date: LocalDate, session: DrawSession): Map<String, Long>; suspend fun getAgentTotals(agentId: Long, date: LocalDate, session: DrawSession): Map<String, Long>; suspend fun confirm(customerId: Long, agentId: Long, date: LocalDate, session: DrawSession, source: String, bets: List<ExpandedBet>): Long; suspend fun edit(entry: BetEntryEntity, bets: List<ExpandedBet>) }
interface WinningNumberRepository { fun observeAll(): Flow<List<WinningNumberEntity>>; fun observe(date: LocalDate, session: DrawSession): Flow<WinningNumberEntity?>; suspend fun get(date: LocalDate, session: DrawSession): WinningNumberEntity?; suspend fun save(date: LocalDate, session: DrawSession, digit: String): Long }
interface ClosedDayRepository { fun observeAll(): Flow<List<ClosedDayEntity>>; suspend fun isClosed(date: LocalDate): Boolean; suspend fun add(date: LocalDate): Long; suspend fun remove(value: ClosedDayEntity) }
interface ClosedNumberRepository { fun observe(agentId: Long): Flow<List<ClosedNumberEntity>>; suspend fun getDigits(agentId: Long): Set<String>; suspend fun add(agentId: Long, digit: String): Long; suspend fun remove(value: ClosedNumberEntity) }
interface LimitRepository { fun observeAllLimit(customerId: Long): Flow<AllLimitEntity?>; fun observeSpecial(customerId: Long): Flow<List<SpecialLimitEntity>>; suspend fun get(customerId: Long): EffectiveLimits; suspend fun setAll(customerId: Long, amount: Long?); suspend fun setSpecial(customerId: Long, digit: String, amount: Long) }

class RoomAgentRepository(private val dao: AgentDao): AgentRepository { override fun observeAll()=dao.observeAll(); override fun observe(id:Long)=dao.observe(id); override suspend fun get(id:Long)=dao.get(id); override suspend fun save(value:AgentEntity)=dao.upsert(value) }
class RoomCustomerRepository(private val dao: CustomerDao): CustomerRepository { override fun observeForAgent(agentId:Long)=dao.observeForAgent(agentId); override fun observe(id:Long)=dao.observe(id); override suspend fun get(id:Long)=dao.get(id); override suspend fun save(value:CustomerEntity)=dao.upsert(value) }
class RoomBetRepository(private val db: LedgerDatabase): BetRepository {
    private val dao=db.betDao()
    override fun observeCustomerTotals(customerId:Long,date:LocalDate,session:DrawSession)=dao.observeCustomerTotals(customerId,date,session)
    override fun observeAgentTotals(agentId:Long,date:LocalDate,session:DrawSession)=dao.observeAgentTotals(agentId,date,session)
    override suspend fun getCustomerTotals(customerId:Long,date:LocalDate,session:DrawSession)=dao.getCustomerTotals(customerId,date,session).associate { it.digit to it.amount }
    override suspend fun getAgentTotals(agentId:Long,date:LocalDate,session:DrawSession)=dao.getAgentTotals(agentId,date,session).associate { it.digit to it.amount }
    override suspend fun confirm(customerId:Long,agentId:Long,date:LocalDate,session:DrawSession,source:String,bets:List<ExpandedBet>):Long = db.withTransaction { require(bets.isNotEmpty()); val now=System.currentTimeMillis(); val id=dao.insertEntry(BetEntryEntity(customerId=customerId,agentId=agentId,drawDate=date,drawSession=session,sourceText=source,createdAt=now,updatedAt=now)); dao.insertLines(bets.map { BetLineEntity(betEntryId=id,digit=it.digit,amount=it.amount) }); id }
    override suspend fun edit(entry:BetEntryEntity,bets:List<ExpandedBet>) = db.withTransaction { dao.updateEntry(entry.copy(updatedAt=System.currentTimeMillis())); dao.deleteLines(entry.id); dao.insertLines(bets.map { BetLineEntity(betEntryId=entry.id,digit=it.digit,amount=it.amount) }) }
}
class RoomWinningNumberRepository(private val dao:WinningNumberDao):WinningNumberRepository { override fun observeAll()=dao.observeAll(); override fun observe(date:LocalDate,session:DrawSession)=dao.observe(date,session); override suspend fun get(date:LocalDate,session:DrawSession)=dao.get(date,session); override suspend fun save(date:LocalDate,session:DrawSession,digit:String):Long { require(com.myanmar.ledger2d.core.domain.BetParser.validDigit(digit)); val now=System.currentTimeMillis(); return dao.upsert(WinningNumberEntity(date=date,session=session,digit=digit,createdAt=now,updatedAt=now)) } }
class RoomClosedDayRepository(private val dao:ClosedDayDao):ClosedDayRepository { override fun observeAll()=dao.observeAll(); override suspend fun isClosed(date:LocalDate)=dao.isClosed(date); override suspend fun add(date:LocalDate):Long { require(!date.isBefore(LocalDate.now())); val now=System.currentTimeMillis(); return dao.upsert(ClosedDayEntity(date=date,createdAt=now,updatedAt=now)) }; override suspend fun remove(value:ClosedDayEntity)=dao.delete(value) }
class RoomClosedNumberRepository(private val dao:ClosedNumberDao):ClosedNumberRepository { override fun observe(agentId:Long)=dao.observe(agentId); override suspend fun getDigits(agentId:Long)=dao.getDigits(agentId).toSet(); override suspend fun add(agentId:Long,digit:String):Long { require(com.myanmar.ledger2d.core.domain.BetParser.validDigit(digit)); val now=System.currentTimeMillis(); return dao.upsert(ClosedNumberEntity(agentId=agentId,digit=digit,createdAt=now,updatedAt=now)) }; override suspend fun remove(value:ClosedNumberEntity)=dao.delete(value) }
class RoomLimitRepository(private val dao:LimitDao):LimitRepository { override fun observeAllLimit(customerId:Long)=dao.observeAllLimit(customerId); override fun observeSpecial(customerId:Long)=dao.observeSpecialLimits(customerId); override suspend fun get(customerId:Long)=EffectiveLimits(dao.getAllLimit(customerId)?.amount,dao.getSpecialLimits(customerId).associate { it.digit to it.amount }); override suspend fun setAll(customerId:Long,amount:Long?) { if(amount==null) dao.clearAll(customerId) else { require(amount>0); val now=System.currentTimeMillis(); dao.upsert(AllLimitEntity(customerId=customerId,amount=amount,createdAt=now,updatedAt=now)) } }; override suspend fun setSpecial(customerId:Long,digit:String,amount:Long) { require(com.myanmar.ledger2d.core.domain.BetParser.validDigit(digit)&&amount>0); val now=System.currentTimeMillis(); dao.upsert(SpecialLimitEntity(customerId=customerId,digit=digit,amount=amount,createdAt=now,updatedAt=now)) } }
